import type { Book } from "./types";

// ---------------------------------------------------------------------------
// Mock book library. All titles are public-domain works, per the project's
// legal strategy (transformative summaries, prefer public domain, attribute).
// In production these objects would be produced by the AI-generation pipeline
// and cached in Postgres — the UI is agnostic to the source.
// ---------------------------------------------------------------------------

export const books: Book[] = [
  {
    slug: "the-art-of-war",
    title: "The Art of War",
    author: "Sun Tzu",
    year: "5th c. BCE",
    category: "non-fiction",
    tags: ["Strategy", "Leadership", "Philosophy"],
    cover: { emoji: "⚔️" },
    tagline: "Timeless strategy for winning without fighting.",
    readingTime: "9 min read",
    rating: 4.7,
    cached: true,
    overview:
      "A concise treatise on military strategy that has shaped leadership and competition for 2,500 years. Sun Tzu argues that the supreme skill is to win before the battle begins — through preparation, deception, positioning, and self-knowledge.",
    summary: [
      "Sun Tzu frames war as a matter of vital importance that must be studied, not left to chance. Every campaign is decided long before contact by five factors: moral influence, weather, terrain, leadership, and doctrine.",
      "Victory belongs to the side that knows both itself and its enemy. Deception is central — appear weak when strong, near when far — so the opponent commits to the wrong response.",
      "The ideal general wins whole: subduing the enemy without prolonged fighting, preserving resources, and adapting endlessly to circumstance like water shaping itself to the ground.",
    ],
    chapters: [
      { number: 1, title: "Laying Plans", summary: "War is decided by five constant factors; calculate them before acting." },
      { number: 2, title: "Waging War", summary: "Prolonged campaigns drain the state; speed and economy win wars." },
      { number: 3, title: "Attack by Stratagem", summary: "The highest excellence is breaking resistance without fighting." },
      { number: 4, title: "Tactical Dispositions", summary: "Secure yourself against defeat first; wait for the enemy's opening." },
      { number: 5, title: "Energy", summary: "Combine direct and indirect methods; use momentum, not effort." },
      { number: 6, title: "Weak Points & Strong", summary: "Be formless. Strike where the enemy is unprepared." },
    ],
    lessons: [
      { title: "Win before you fight", detail: "Preparation and positioning decide outcomes; the actual clash only confirms them." },
      { title: "Know yourself and the other", detail: "Self-knowledge plus intelligence about the opponent removes most risk of defeat." },
      { title: "Speed beats perfection", detail: "A good plan executed now outperforms a perfect plan executed too late." },
      { title: "Be like water", detail: "Have no fixed shape; adapt tactics endlessly to the terrain in front of you." },
    ],
    timeline: [
      { label: "Prepare", title: "Assess the five factors", detail: "Weigh moral influence, weather, terrain, leadership, and doctrine." },
      { label: "Position", title: "Secure against defeat", detail: "Make yourself unassailable before seeking to attack." },
      { label: "Deceive", title: "Shape the enemy", detail: "Use misdirection so the opponent defends the wrong point." },
      { label: "Strike", title: "Exploit the opening", detail: "Concentrate force where the enemy is weakest and unprepared." },
      { label: "Win whole", title: "Subdue, don't destroy", detail: "Preserve resources; end conflict quickly and decisively." },
    ],
    characters: [],
    mindMap: [
      { id: "root", label: "The Art of War", parent: null },
      { id: "plan", label: "Planning & Calculation", parent: "root" },
      { id: "decep", label: "Deception", parent: "root" },
      { id: "terr", label: "Terrain & Positioning", parent: "root" },
      { id: "lead", label: "Leadership", parent: "root" },
      { id: "five", label: "Five Factors", parent: "plan" },
      { id: "spy", label: "Foreknowledge / Spies", parent: "decep" },
      { id: "water", label: "Be Formless", parent: "terr" },
      { id: "disc", label: "Discipline & Morale", parent: "lead" },
    ],
    sketches: [
      { caption: "A general reading the terrain before dawn", emoji: "🏔️" },
      { caption: "Water flowing around stone — adaptability", emoji: "🌊" },
      { caption: "Two armies, one already decided", emoji: "🚩" },
    ],
    qa: [
      { q: "What is the main idea?", a: "The supreme art is to win without fighting — through preparation, deception, and positioning that make the outcome inevitable before battle." },
      { q: "How is this useful today?", a: "Business, negotiation, and sport all reward the same discipline: know yourself and your competitor, move fast, and attack unguarded openings." },
      { q: "What does 'be like water' mean?", a: "Have no rigid plan. Just as water takes the shape of its container, tactics should conform to the specific situation in front of you." },
    ],
  },

  {
    slug: "meditations",
    title: "Meditations",
    author: "Marcus Aurelius",
    year: "c. 170–180 CE",
    category: "non-fiction",
    tags: ["Stoicism", "Philosophy", "Self-improvement"],
    cover: { emoji: "🏛️" },
    tagline: "A Roman emperor's private notes on how to live.",
    readingTime: "11 min read",
    rating: 4.8,
    cached: true,
    overview:
      "Never meant for publication, Meditations is the personal journal of the emperor Marcus Aurelius. Across twelve books he reminds himself to master his judgments, accept nature, serve the common good, and meet death without fear.",
    summary: [
      "Marcus writes to steady himself. The core Stoic move recurs on every page: separate what you control (your judgments and actions) from what you do not (everything else), and invest only in the former.",
      "External events are neutral; suffering comes from our opinions about them. Change the judgment and the disturbance dissolves.",
      "We exist for one another. Duty to the common good, gratitude for what nature lends us, and calm acceptance of mortality form a practical ethics for daily life.",
    ],
    chapters: [
      { number: 1, title: "Debts and Lessons", summary: "Marcus thanks the people who shaped his character." },
      { number: 2, title: "On the River Gran", summary: "Begin each day expecting difficulty; you carry reason within you." },
      { number: 4, title: "The Inner Citadel", summary: "Retreat into your own mind — the one place always available and calm." },
      { number: 6, title: "Nature and Change", summary: "All things transform; resisting change is resisting the universe." },
      { number: 8, title: "Opinion and Disturbance", summary: "Remove the judgment 'I am harmed' and the harm itself is gone." },
      { number: 12, title: "On Death", summary: "Leave life as an actor leaves the stage — gracefully, on cue." },
    ],
    lessons: [
      { title: "Control the controllable", detail: "Your judgments and choices are yours; nothing else is. Spend energy only there." },
      { title: "Events are neutral", detail: "It is opinion, not the event, that wounds. Revise the opinion." },
      { title: "Live for others", detail: "We are made for cooperation, like hands and eyes; serve the common good." },
      { title: "Memento mori", detail: "Remembering death clarifies priorities and dissolves petty anxieties." },
    ],
    timeline: [
      { label: "Book I", title: "Gratitude", detail: "Cataloguing the virtues learned from family and teachers." },
      { label: "Book II", title: "Discipline", detail: "Facing each day's obstacles with reason and duty." },
      { label: "Book IV", title: "The inner citadel", detail: "Finding calm by withdrawing into one's own mind." },
      { label: "Book VII", title: "Acceptance", detail: "Aligning the will with nature's constant change." },
      { label: "Book XII", title: "Departure", detail: "Meeting mortality with composure and gratitude." },
    ],
    characters: [],
    mindMap: [
      { id: "root", label: "Meditations", parent: null },
      { id: "control", label: "Dichotomy of Control", parent: "root" },
      { id: "judge", label: "Judgment", parent: "root" },
      { id: "nature", label: "Living with Nature", parent: "root" },
      { id: "duty", label: "Duty to Others", parent: "root" },
      { id: "control2", label: "Focus on Choice", parent: "control" },
      { id: "opinion", label: "Events are Neutral", parent: "judge" },
      { id: "change", label: "Accept Change", parent: "nature" },
      { id: "death", label: "Memento Mori", parent: "nature" },
      { id: "common", label: "Common Good", parent: "duty" },
    ],
    sketches: [
      { caption: "An emperor writing by lamplight in a war tent", emoji: "🕯️" },
      { caption: "A calm citadel above a storm", emoji: "🏯" },
      { caption: "An hourglass — memento mori", emoji: "⏳" },
    ],
    qa: [
      { q: "What is Stoicism in one line?", a: "Focus entirely on what you control — your judgments and actions — and accept everything else with equanimity." },
      { q: "Why did he write it?", a: "For himself. Meditations is a private journal of reminders, never intended for readers, which is why it feels so honest." },
      { q: "What is the 'inner citadel'?", a: "Your own mind — a refuge of calm you can retreat into at any moment, no matter what is happening outside." },
    ],
  },

  {
    slug: "pride-and-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: "1813",
    category: "fiction",
    tags: ["Romance", "Classic", "Social satire"],
    cover: { emoji: "💌" },
    tagline: "First impressions are rarely the truth.",
    readingTime: "14 min read",
    rating: 4.9,
    cached: true,
    overview:
      "Elizabeth Bennet, sharp-witted and proud of her judgment, clashes with the wealthy, aloof Mr. Darcy. As misjudgments unravel, both must confront their own pride and prejudice before love becomes possible.",
    summary: [
      "In Regency England, the Bennet family's five unmarried daughters face social pressure to marry well. When the rich Mr. Bingley and his friend Mr. Darcy arrive, Elizabeth is put off by Darcy's cold pride.",
      "A web of misunderstandings — fueled by the charming liar Wickham and Darcy's own reserve — deepens Elizabeth's prejudice, and she rejects his first proposal.",
      "A letter reveals the truth, and as each corrects their misjudgment of the other, mutual respect grows into love. The novel satirizes class and marriage while insisting on the primacy of character.",
    ],
    chapters: [
      { number: 1, title: "A Truth Universally Acknowledged", summary: "Mrs. Bennet schemes to marry her daughters to the new arrivals." },
      { number: 6, title: "The Assembly", summary: "Darcy slights Elizabeth; Bingley falls for Jane." },
      { number: 19, title: "The First Proposal", summary: "Elizabeth rejects Mr. Collins, defying her mother." },
      { number: 34, title: "Darcy's Proposal", summary: "Darcy proposes and is refused; Elizabeth accuses him." },
      { number: 35, title: "The Letter", summary: "Darcy's letter reframes Wickham and reveals his true motives." },
      { number: 58, title: "Understanding", summary: "Pride and prejudice give way; Elizabeth and Darcy reconcile." },
    ],
    lessons: [
      { title: "First impressions mislead", detail: "Both leads are wrong about each other; real knowledge takes time and humility." },
      { title: "Pride cuts both ways", detail: "Darcy's rank-pride and Elizabeth's pride in her own perception each blind them." },
      { title: "Marry for character", detail: "Austen contrasts unions of convenience with Elizabeth's insistence on respect and love." },
      { title: "Growth requires self-examination", detail: "Change comes only when each admits their own error, not the other's." },
    ],
    timeline: [
      { label: "Ch. 1", title: "New neighbours", detail: "Bingley and Darcy arrive at Netherfield." },
      { label: "Ch. 6", title: "The slight", detail: "Darcy refuses to dance with Elizabeth; prejudice begins." },
      { label: "Ch. 34", title: "First proposal", detail: "Darcy proposes and is angrily rejected." },
      { label: "Ch. 35", title: "The letter", detail: "The truth about Wickham upends Elizabeth's view." },
      { label: "Ch. 58", title: "Reconciliation", detail: "Both humbled, they finally understand each other." },
    ],
    characters: [
      { name: "Elizabeth Bennet", role: "Protagonist", description: "Witty, independent second Bennet daughter who prizes her own judgment.", connections: ["Fitzwilliam Darcy", "Jane Bennet"] },
      { name: "Fitzwilliam Darcy", role: "Love interest", description: "Wealthy, proud, and reserved — hiding genuine integrity.", connections: ["Elizabeth Bennet", "Charles Bingley"] },
      { name: "Jane Bennet", role: "Elder sister", description: "Gentle and hopeful; falls for Bingley.", connections: ["Charles Bingley", "Elizabeth Bennet"] },
      { name: "Charles Bingley", role: "Suitor", description: "Amiable, wealthy friend of Darcy.", connections: ["Jane Bennet", "Fitzwilliam Darcy"] },
      { name: "George Wickham", role: "Antagonist", description: "Charming militia officer whose lies stoke Elizabeth's prejudice.", connections: ["Elizabeth Bennet", "Fitzwilliam Darcy"] },
    ],
    mindMap: [
      { id: "root", label: "Pride & Prejudice", parent: null },
      { id: "pride", label: "Pride", parent: "root" },
      { id: "prej", label: "Prejudice", parent: "root" },
      { id: "class", label: "Class & Marriage", parent: "root" },
      { id: "growth", label: "Self-Growth", parent: "root" },
      { id: "darcy", label: "Darcy's Rank-Pride", parent: "pride" },
      { id: "eliz", label: "Elizabeth's Judgment", parent: "prej" },
      { id: "wick", label: "Wickham's Lies", parent: "prej" },
      { id: "money", label: "Marriage for Security", parent: "class" },
      { id: "letter", label: "The Turning Letter", parent: "growth" },
    ],
    sketches: [
      { caption: "A grand ballroom at Netherfield", emoji: "💃" },
      { caption: "A refused proposal in the rain", emoji: "🌧️" },
      { caption: "A letter that changes everything", emoji: "✉️" },
    ],
    qa: [
      { q: "Who are the two leads?", a: "Elizabeth Bennet, clever and proud of her judgment, and Mr. Darcy, wealthy and reserved. Both misjudge each other badly at first." },
      { q: "What does the title mean?", a: "Darcy embodies pride (of rank), Elizabeth prejudice (in her quick judgments). Each flaw must be overcome for love to work." },
      { q: "Why does Elizabeth reject Darcy?", a: "His arrogant first proposal, plus Wickham's lies and Darcy's meddling in Jane's romance, convince her he's proud and cruel — until his letter reveals the truth." },
    ],
  },

  {
    slug: "frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    year: "1818",
    category: "fiction",
    tags: ["Gothic", "Science fiction", "Tragedy"],
    cover: { emoji: "⚡" },
    tagline: "The first science fiction novel — and a warning.",
    readingTime: "13 min read",
    rating: 4.6,
    cached: false,
    overview:
      "Ambitious young scientist Victor Frankenstein discovers how to animate dead matter and creates a living being — then abandons it in horror. Rejected by all, the creature turns to vengeance, destroying everyone Victor loves.",
    summary: [
      "Framed as letters from the explorer Robert Walton, the novel recounts Victor Frankenstein's obsessive quest to conquer death. He assembles and animates a creature, then flees, repulsed by what he has made.",
      "Abandoned and shunned for his appearance, the intelligent, eloquent creature teaches himself language and morality, but endless rejection turns him to rage. He demands a companion; Victor refuses.",
      "The creature murders Victor's family one by one. The two pursue each other to the Arctic, where Victor dies and the creature, alone and remorseful, vanishes into the ice. The novel questions ambition, responsibility, and who the real monster is.",
    ],
    chapters: [
      { number: 1, title: "Walton's Letters", summary: "An Arctic explorer rescues a dying Victor and hears his tale." },
      { number: 4, title: "The Spark of Life", summary: "Victor discovers the secret of animation and begins his work." },
      { number: 5, title: "The Creation", summary: "The creature awakens; Victor recoils and abandons it." },
      { number: 11, title: "The Creature's Story", summary: "The creature recounts learning to speak and being rejected by all." },
      { number: 17, title: "The Bargain", summary: "The creature demands a mate; Victor agrees, then destroys her." },
      { number: 24, title: "The Pursuit", summary: "Victor chases the creature to the Arctic and dies; the creature mourns." },
    ],
    lessons: [
      { title: "Ambition needs responsibility", detail: "Victor's genius is undone by his refusal to care for what he creates." },
      { title: "Rejection breeds monsters", detail: "The creature is born gentle; cruelty and isolation make it vengeful." },
      { title: "Beware playing god", detail: "Shelley warns that power over life without wisdom or ethics ends in ruin." },
      { title: "We are shaped by how we're treated", detail: "Both Victor and the creature become who circumstance and choice make them." },
    ],
    timeline: [
      { label: "Frame", title: "Walton's expedition", detail: "An explorer finds Victor stranded on the ice." },
      { label: "Rise", title: "The creation", detail: "Victor animates the creature, then abandons it in horror." },
      { label: "Turn", title: "The creature learns", detail: "Self-educated but universally rejected, it grows bitter." },
      { label: "Fall", title: "Revenge", detail: "The creature kills Victor's loved ones after the broken bargain." },
      { label: "End", title: "The Arctic", detail: "Victor dies; the remorseful creature disappears into the north." },
    ],
    characters: [
      { name: "Victor Frankenstein", role: "Protagonist", description: "Brilliant, obsessive scientist who creates life and abandons it.", connections: ["The Creature", "Robert Walton", "Elizabeth Lavenza"] },
      { name: "The Creature", role: "Antagonist / victim", description: "Intelligent, eloquent being turned vengeful by universal rejection.", connections: ["Victor Frankenstein"] },
      { name: "Robert Walton", role: "Narrator", description: "Arctic explorer whose letters frame the story; mirrors Victor's ambition.", connections: ["Victor Frankenstein"] },
      { name: "Elizabeth Lavenza", role: "Victor's beloved", description: "Victor's adoptive cousin and fiancée, killed by the creature.", connections: ["Victor Frankenstein"] },
      { name: "Henry Clerval", role: "Best friend", description: "Victor's loyal friend, another of the creature's victims.", connections: ["Victor Frankenstein"] },
    ],
    mindMap: [
      { id: "root", label: "Frankenstein", parent: null },
      { id: "amb", label: "Ambition", parent: "root" },
      { id: "resp", label: "Responsibility", parent: "root" },
      { id: "iso", label: "Isolation", parent: "root" },
      { id: "nature", label: "Nature vs. Nurture", parent: "root" },
      { id: "god", label: "Playing God", parent: "amb" },
      { id: "abandon", label: "Abandonment", parent: "resp" },
      { id: "reject", label: "Rejection", parent: "iso" },
      { id: "monster", label: "Who is the Monster?", parent: "nature" },
    ],
    sketches: [
      { caption: "Lightning over a laboratory", emoji: "⚡" },
      { caption: "A lone figure in the Arctic snow", emoji: "🧊" },
      { caption: "A creature learning by firelight", emoji: "🔥" },
    ],
    qa: [
      { q: "Who is the monster?", a: "Shelley leaves it ambiguous. The creature commits murders, but Victor's abandonment and cruelty arguably create the monster — the title refers to the maker, not the made." },
      { q: "Why is it important?", a: "Often called the first true science-fiction novel, it launched enduring questions about scientific responsibility and the ethics of creating life." },
      { q: "What does the creature want?", a: "Acceptance and companionship. Only after being rejected by everyone — including his own maker — does he turn to revenge." },
    ],
  },

  {
    slug: "the-prince",
    title: "The Prince",
    author: "Niccolò Machiavelli",
    year: "1532",
    category: "non-fiction",
    tags: ["Politics", "Strategy", "Leadership"],
    cover: { emoji: "👑" },
    tagline: "How power is really won, held, and lost.",
    readingTime: "10 min read",
    rating: 4.5,
    cached: true,
    overview:
      "A blunt handbook on acquiring and keeping political power, written for the rulers of Renaissance Italy. Machiavelli sets aside how princes ought to behave and describes how they must behave to survive — arguing that a leader should be guided by results, not by inherited moral ideals.",
    summary: [
      "Machiavelli surveys the kinds of states and how each is won: by ability, by luck, by crime, or by the favour of others. States taken by one's own skill are hard to win but easy to hold; those taken by fortune are the reverse.",
      "A prince must master both the 'lion' and the 'fox' — force and cunning. It is safer to be feared than loved if you cannot be both, but a prince must never be hated, which means never seizing his subjects' property or their women.",
      "Fortune governs roughly half of what happens; the rest is up to us. The leader who adapts his methods to the times prospers; the one who clings to a single style eventually meets a moment it doesn't fit.",
    ],
    chapters: [
      { number: 1, title: "Kinds of Principalities", summary: "New states are harder to hold than hereditary ones, which run on habit." },
      { number: 6, title: "Won by One's Own Arms", summary: "Founders who rely on their own ability, not luck, build lasting power — but must be able to enforce their vision." },
      { number: 15, title: "How Princes Should Act", summary: "Study how people really behave, not how they should; a ruler who is always good among the not-good will be ruined." },
      { number: 17, title: "Cruelty and Mercy", summary: "Better feared than loved if you must choose — but avoid being hated above all." },
      { number: 18, title: "Keeping Faith", summary: "A prince should appear honest, merciful and religious, and be ready to act otherwise when survival demands it." },
      { number: 25, title: "Fortune", summary: "Fortune is a river that floods when unchecked; the wise build dykes in calm weather. Boldness tends to master her." },
    ],
    lessons: [
      { title: "Judge by results", detail: "In Machiavelli's frame, an action's worth is measured by what it secures, not by the intention behind it." },
      { title: "Own your means", detail: "Power borrowed from allies, mercenaries or luck evaporates; power built on your own capacity endures." },
      { title: "Manage perception", detail: "What people believe about a leader shapes events as much as what the leader actually does." },
      { title: "Adapt or fall", detail: "The same tactics that win in one climate lose in another; rigidity is the quiet killer of rulers." },
    ],
    timeline: [
      { label: "Acquire", title: "Take the state", detail: "By ability, fortune, crime, or the choice of the people or nobles." },
      { label: "Secure", title: "Neutralise rivals", detail: "Remove the old ruling line; keep laws and taxes familiar." },
      { label: "Arm", title: "Raise your own forces", detail: "Rely on citizen soldiers, not mercenaries or auxiliaries." },
      { label: "Govern", title: "Balance fear and favour", detail: "Punish decisively and once; distribute benefits slowly." },
      { label: "Endure", title: "Ride fortune's swings", detail: "Adapt method to circumstance; act boldly when the moment turns." },
    ],
    characters: [],
    mindMap: [
      { id: "root", label: "The Prince", parent: null },
      { id: "power", label: "Acquiring Power", parent: "root" },
      { id: "hold", label: "Holding Power", parent: "root" },
      { id: "virtue", label: "Virtù & Fortuna", parent: "root" },
      { id: "ethics", label: "Ends & Means", parent: "root" },
      { id: "arms", label: "Your Own Arms", parent: "power" },
      { id: "fear", label: "Feared, Not Hated", parent: "hold" },
      { id: "adapt", label: "Adapt to the Times", parent: "virtue" },
      { id: "appear", label: "Appearance vs. Reality", parent: "ethics" },
    ],
    sketches: [
      { caption: "A fox and a lion sharing one crown", emoji: "🦊" },
      { caption: "A river breaking its banks", emoji: "🌊" },
      { caption: "A ruler weighing a scale of coins and swords", emoji: "⚖️" },
    ],
    qa: [
      { q: "Is it a defence of tyranny?", a: "Debated for centuries. It reads as cold advice to rulers, but some see it as a sly exposé of how power works — or a warning dressed as a manual." },
      { q: "What does 'the ends justify the means' mean here?", a: "Machiavelli never wrote that exact line, but he argues a ruler's actions are judged by whether they preserve the state, not by conventional morality." },
      { q: "Why still read it?", a: "It's the founding text of realist political thought — a clear-eyed look at incentives, perception and power that shows up in business and diplomacy today." },
    ],
  },

  {
    slug: "tao-te-ching",
    title: "Tao Te Ching",
    author: "Laozi",
    year: "c. 4th c. BCE",
    category: "non-fiction",
    tags: ["Philosophy", "Taoism", "Self-improvement"],
    cover: { emoji: "☯️" },
    tagline: "The strength of water, the wisdom of yielding.",
    readingTime: "9 min read",
    rating: 4.7,
    cached: true,
    overview:
      "Eighty-one short verses at the root of Taoism. The Tao — 'the Way' — is the nameless source and pattern of everything. The book teaches that we align with it not by striving harder but by acting naturally, yielding where force would break, and doing less so that little is left undone.",
    summary: [
      "The Tao that can be named is not the eternal Tao. Language and categories carve the world into opposites — being and non-being, hard and soft — but these arise together and define each other.",
      "The central practice is wu wei: effortless action. Like water, which is soft yet wears down stone and always finds the low place, the sage accomplishes things without contention, leadership without domination.",
      "Simplicity, humility and knowing when to stop are the recurring virtues. The person who is content is already rich; the leader who trusts people governs best by being barely felt.",
    ],
    chapters: [
      { number: 1, title: "The Nameless", summary: "The Tao precedes names; naming begins the ten thousand things." },
      { number: 8, title: "Like Water", summary: "The highest good is like water — it benefits all and competes with none, settling where others disdain to be." },
      { number: 11, title: "The Use of Emptiness", summary: "A wheel's usefulness is in the hollow hub; a room's in its empty space. Non-being does the work." },
      { number: 17, title: "The Best Leaders", summary: "The best ruler is one whose people barely know he exists; when the work is done they say, 'we did it ourselves.'" },
      { number: 33, title: "Knowing Others, Knowing Self", summary: "To know others is intelligence; to know yourself is wisdom. Mastering yourself is true power." },
      { number: 63, title: "Doing Without Doing", summary: "Meet the great while it is small; handle the hard while it is easy. Great things are done by not making them great." },
    ],
    lessons: [
      { title: "Yield to overcome", detail: "The soft outlasts the hard. Flexibility survives storms that shatter rigid things." },
      { title: "Act with the grain", detail: "Wu wei is not passivity — it's action so aligned with the situation that it seems to cost no effort." },
      { title: "Enough is a feast", detail: "Contentment, not accumulation, is the source of lasting wealth and peace." },
      { title: "Lead invisibly", detail: "The strongest influence leaves people feeling they acted freely, not that they were managed." },
    ],
    timeline: [
      { label: "Source", title: "The nameless Tao", detail: "Before heaven and earth, the undivided origin." },
      { label: "Division", title: "The ten thousand things", detail: "Names and opposites arise; the world becomes many." },
      { label: "Practice", title: "Wu wei", detail: "The sage acts without forcing, like water finding its level." },
      { label: "Virtue", title: "Simplicity & humility", detail: "Desire less, contend less, return to the uncarved block." },
      { label: "Return", title: "Back to the Tao", detail: "All things flourish and return to their root; this is stillness." },
    ],
    characters: [],
    mindMap: [
      { id: "root", label: "Tao Te Ching", parent: null },
      { id: "tao", label: "The Tao (the Way)", parent: "root" },
      { id: "wuwei", label: "Wu Wei", parent: "root" },
      { id: "virtue", label: "Te (Virtue)", parent: "root" },
      { id: "leader", label: "Leadership", parent: "root" },
      { id: "water", label: "Be Like Water", parent: "wuwei" },
      { id: "empty", label: "Use of Emptiness", parent: "tao" },
      { id: "simple", label: "Simplicity", parent: "virtue" },
      { id: "invisible", label: "Lead Unseen", parent: "leader" },
    ],
    sketches: [
      { caption: "Water shaping stone over centuries", emoji: "💧" },
      { caption: "An empty bowl, useful for its hollow", emoji: "🥣" },
      { caption: "An uncarved block of wood", emoji: "🪵" },
    ],
    qa: [
      { q: "What is the Tao?", a: "The Way — the source, pattern and flow of all existence. It can't be fully named or grasped, only aligned with." },
      { q: "Does wu wei mean doing nothing?", a: "No. It means acting without strain or force — moving with a situation rather than against it, so results come naturally." },
      { q: "How is it used today?", a: "Leadership, design, negotiation and stress management all borrow its core idea: less force, better timing, and knowing when to stop." },
    ],
  },

  {
    slug: "walden",
    title: "Walden",
    author: "Henry David Thoreau",
    year: "1854",
    category: "non-fiction",
    tags: ["Philosophy", "Nature", "Self-improvement"],
    cover: { emoji: "🌲" },
    tagline: "Live deliberately; want less; wake up.",
    readingTime: "13 min read",
    rating: 4.4,
    cached: true,
    overview:
      "Thoreau's account of two years living simply in a cabin he built by Walden Pond in Massachusetts. Part experiment, part manifesto, it argues that most people are so busy earning a living that they never live — and that a deliberately simple life frees time, attention and conscience.",
    summary: [
      "Thoreau opens with 'Economy': a hard-nosed accounting of what a life actually costs. Food, shelter, clothing and fuel are the true necessities; most of what we work for is luxury that ends up owning us.",
      "He describes the daily texture of the experiment — building the cable, growing beans, reading, listening to the pond and the railroad, receiving occasional visitors. Solitude, he finds, is not loneliness but company with nature and thought.",
      "The closing chapters turn outward: a defence of nonconformity and an insistence that each person has a different drummer to march to. 'If a man does not keep pace with his companions, perhaps it is because he hears a different drummer.'",
    ],
    chapters: [
      { number: 1, title: "Economy", summary: "A ledger of real needs vs. inherited wants; most labour buys things that cost us our freedom." },
      { number: 2, title: "Where I Lived, and What I Lived For", summary: "He went to the woods to live deliberately and 'not, when I came to die, discover that I had not lived.'" },
      { number: 3, title: "Reading", summary: "Great books are the wealth of the world, but few read them; a town should be a patron of learning." },
      { number: 4, title: "Sounds", summary: "The bells, the trains, the whip-poor-wills — the day itself is enough entertainment for an attentive mind." },
      { number: 5, title: "Solitude", summary: "He is never lonely near the pond; nature and one's own thoughts are sufficient society." },
      { number: 18, title: "Conclusion", summary: "Advance confidently toward your dreams; simplify; march to whatever drummer you hear, however measured or far away." },
    ],
    lessons: [
      { title: "Count the true cost", detail: "The price of a thing is the amount of life you exchange for it. Most purchases are dearer than they look." },
      { title: "Simplify, simplify", detail: "Fewer possessions and obligations mean more time and attention for what actually matters to you." },
      { title: "Be awake", detail: "Living deliberately means paying full attention to the present, not sleepwalking through routine." },
      { title: "Trust your own drummer", detail: "Falling out of step with the crowd is often a sign you're following something truer." },
    ],
    timeline: [
      { label: "1845", title: "Move to the pond", detail: "Thoreau builds a small cabin on Emerson's land at Walden." },
      { label: "Spring", title: "Plant the bean-field", detail: "He farms just enough to cover his few needs and fund his time." },
      { label: "Summer", title: "Live the days", detail: "Reading, walking, observing; solitude turns rich rather than lonely." },
      { label: "Winter", title: "The frozen pond", detail: "He surveys its depth, dispelling local myths, and studies the ice." },
      { label: "1847", title: "Leave", detail: "He returns to town with the experiment's lessons: 'I had several more lives to live.'" },
    ],
    characters: [],
    mindMap: [
      { id: "root", label: "Walden", parent: null },
      { id: "econ", label: "Economy of Life", parent: "root" },
      { id: "delib", label: "Deliberate Living", parent: "root" },
      { id: "nature", label: "Nature & Attention", parent: "root" },
      { id: "self", label: "Self-Reliance", parent: "root" },
      { id: "needs", label: "True Necessities", parent: "econ" },
      { id: "awake", label: "Being Awake", parent: "delib" },
      { id: "solitude", label: "Solitude", parent: "nature" },
      { id: "drummer", label: "A Different Drummer", parent: "self" },
    ],
    sketches: [
      { caption: "A one-room cabin among pines", emoji: "🏕️" },
      { caption: "A ledger listing beans, rice and nails", emoji: "🧾" },
      { caption: "A still pond mirroring the sky", emoji: "🪞" },
    ],
    qa: [
      { q: "Was Thoreau a hermit?", a: "Not really — Walden Pond was a short walk from town, he had visitors, and he left after two years. The point was the experiment, not permanent isolation." },
      { q: "What's the main idea?", a: "That deliberate simplicity buys back the time and attention most people trade away, letting you actually live rather than just make a living." },
      { q: "How does it connect to 'Civil Disobedience'?", a: "Both come from the same conviction: that conscience outranks convention, and each person must answer for their own life and choices." },
    ],
  },

  {
    slug: "the-republic",
    title: "The Republic",
    author: "Plato",
    year: "c. 375 BCE",
    category: "non-fiction",
    tags: ["Philosophy", "Politics", "Ethics"],
    cover: { emoji: "🏛️" },
    tagline: "What is justice — in a city, and in a soul?",
    readingTime: "14 min read",
    rating: 4.6,
    cached: true,
    overview:
      "A dialogue in which Socrates and friends try to define justice by building an ideal city in speech. Along the way it covers education, censorship, the nature of knowledge, the famous allegory of the cave, and the claim that the just life is happier than the unjust — even when injustice goes unpunished.",
    summary: [
      "The conversation starts with rival definitions of justice — 'telling the truth and paying debts,' 'helping friends and harming enemies,' and Thrasymachus's cynical 'the advantage of the stronger.' Socrates finds each wanting.",
      "To see justice writ large, they design a city with three classes: producers, guardians (soldiers), and rulers. Justice, they conclude, is each part doing its own work and not meddling with the others — and the same holds for the three parts of the soul: reason, spirit and appetite.",
      "The ideal ruler is the philosopher, who has left the 'cave' of shadows and seen the Form of the Good. Plato then ranks flawed regimes — timocracy, oligarchy, democracy, tyranny — showing how each decays into the next, and ends arguing that the just soul is the freest and happiest.",
    ],
    chapters: [
      { number: 1, title: "What Is Justice?", summary: "Cephalus, Polemarchus and Thrasymachus offer definitions; Socrates dismantles each." },
      { number: 2, title: "The City in Speech", summary: "To study justice, build a city from scratch and watch where it appears." },
      { number: 4, title: "The Tripartite Soul", summary: "Reason, spirit and appetite mirror the city's rulers, guardians and producers; justice is their right order." },
      { number: 7, title: "The Allegory of the Cave", summary: "Prisoners mistake shadows for reality; education is the painful turn toward the light of true knowledge." },
      { number: 8, title: "The Decline of Regimes", summary: "Aristocracy decays into timocracy, oligarchy, democracy and finally tyranny, each driven by a different desire." },
      { number: 9, title: "The Happiest Life", summary: "The tyrant, enslaved by appetite, is the most wretched; the just, reason-ruled soul is the most free and content." },
    ],
    lessons: [
      { title: "Justice is inner order", detail: "For Plato, a just person is one whose reason governs spirit and appetite — not merely one who obeys laws." },
      { title: "Look for the pattern at scale", detail: "Hard questions about the individual can be clearer when examined in a larger system, like a city." },
      { title: "Knowledge vs. opinion", detail: "Most people navigate by shadows and hearsay; real understanding requires turning toward first principles." },
      { title: "Regimes track characters", detail: "The politics a society tolerates reflects what its citizens most desire — honour, money, freedom, or power." },
    ],
    timeline: [
      { label: "Book I", title: "The question", detail: "A dinner argument: what is justice, and does it pay?" },
      { label: "Book II–IV", title: "The city built", detail: "Three classes emerge; justice is each doing its own part." },
      { label: "Book V–VII", title: "Philosopher-kings", detail: "Only those who know the Good should rule; the cave allegory explains why." },
      { label: "Book VIII–IX", title: "The decline", detail: "Regimes and souls degrade step by step down to tyranny." },
      { label: "Book X", title: "The verdict", detail: "The just life wins on its own terms — and, the myth of Er adds, beyond this life too." },
    ],
    characters: [
      { name: "Socrates", role: "Narrator & questioner", description: "Leads the inquiry, building the ideal city to test what justice really is.", connections: ["Glaucon", "Thrasymachus"] },
      { name: "Glaucon", role: "Chief interlocutor", description: "Plato's brother; presses Socrates to prove justice is good in itself, not just for its rewards.", connections: ["Socrates", "Adeimantus"] },
      { name: "Adeimantus", role: "Interlocutor", description: "Plato's other brother; raises the objection that people praise justice only for its consequences.", connections: ["Socrates", "Glaucon"] },
      { name: "Thrasymachus", role: "Antagonist", description: "A sophist who argues justice is merely 'the advantage of the stronger.'", connections: ["Socrates"] },
      { name: "Cephalus", role: "Elder host", description: "Opens the dialogue with a conventional, comfortable view of justice as honesty and paying debts.", connections: ["Socrates", "Polemarchus"] },
    ],
    mindMap: [
      { id: "root", label: "The Republic", parent: null },
      { id: "justice", label: "Justice", parent: "root" },
      { id: "city", label: "The Ideal City", parent: "root" },
      { id: "soul", label: "The Tripartite Soul", parent: "root" },
      { id: "know", label: "Knowledge", parent: "root" },
      { id: "classes", label: "Three Classes", parent: "city" },
      { id: "philking", label: "Philosopher-Kings", parent: "city" },
      { id: "cave", label: "Allegory of the Cave", parent: "know" },
      { id: "decline", label: "Decline of Regimes", parent: "justice" },
    ],
    sketches: [
      { caption: "Prisoners watching shadows on a cave wall", emoji: "🕳️" },
      { caption: "A city divided into three tiers", emoji: "🏙️" },
      { caption: "A soul as a charioteer with two horses", emoji: "🐎" },
    ],
    qa: [
      { q: "What is the cave allegory?", a: "Prisoners chained facing a wall take shadows for reality. One is freed, sees the sun, and returns — but the others, comfortable with shadows, resist him. It pictures education and the difficulty of truth." },
      { q: "Would Plato's city work?", a: "Most readers think not — it requires censorship, a rigid class system and rulers with near-perfect wisdom. Whether Plato meant it literally is still debated." },
      { q: "Why does justice 'pay'?", a: "Because for Plato a just soul is internally harmonious and free, while the unjust soul is at war with itself and enslaved to its appetites — miserable even if it escapes punishment." },
    ],
  },

  {
    slug: "narrative-of-the-life-of-frederick-douglass",
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    year: "1845",
    category: "non-fiction",
    tags: ["Autobiography", "History", "Freedom"],
    cover: { emoji: "⛓️" },
    tagline: "How a boy taught himself to read his way to freedom.",
    readingTime: "12 min read",
    rating: 4.9,
    cached: true,
    overview:
      "Douglass's first autobiography, written to prove that a formerly enslaved man could produce such a book. It recounts his birth into slavery in Maryland, the brutality he witnessed and survived, his secret pursuit of literacy, his turning point in a fight with a 'slave-breaker,' and his escape to the North — exposing slavery from the inside with unmatched clarity.",
    summary: [
      "Douglass is born on a plantation, separated from his mother as an infant, and denied even the knowledge of his own birthday — a deliberate stripping of identity that he identifies as one of slavery's core mechanisms.",
      "Sent to Baltimore, he begins learning the alphabet from his enslaver's wife until her husband forbids it, telling her that literacy would make a slave 'unmanageable.' Douglass realises this is the pathway from slavery to freedom and pursues reading in secret, trading bread to poor white boys for lessons.",
      "Hired out to Edward Covey, a man paid to break enslaved people's spirits, Douglass reaches his lowest point — then physically resists Covey in a two-hour fight and is never whipped again. 'You have seen how a man was made a slave; you shall see how a slave was made a man.' He escapes to New York in 1838 and becomes an abolitionist speaker.",
    ],
    chapters: [
      { number: 1, title: "Birth and Origins", summary: "Born into slavery, separated from his mother, denied his age — identity erased from the start." },
      { number: 4, title: "Life on the Plantation", summary: "Casual, unpunished murders of enslaved people establish the total lawlessness of the system." },
      { number: 6, title: "The Forbidden Alphabet", summary: "Mrs. Auld teaches him letters; Mr. Auld stops it, revealing that literacy is the enslaver's real fear." },
      { number: 7, title: "Learning to Read", summary: "Douglass tricks lessons out of white boys and reads 'The Columbian Orator'; knowledge brings both power and torment." },
      { number: 10, title: "The Fight with Covey", summary: "After months of being broken, he fights back and wins — the psychological turning point of his life." },
      { number: 11, title: "Escape", summary: "In 1838 he reaches New York and freedom, withholding the method so others can still use it." },
    ],
    lessons: [
      { title: "Literacy is power", detail: "Slaveholders banned reading because an informed mind cannot be fully owned; education is a political act." },
      { title: "Dehumanisation is deliberate", detail: "Erasing birthdays, families and names was a system, not an accident — designed to prevent a sense of self." },
      { title: "Resistance restores the self", detail: "Douglass dates his return to manhood not to his escape but to the moment he physically refused to be beaten." },
      { title: "Religion can be a mask", detail: "He distinguishes the 'Christianity of Christ' from the 'slaveholding religion' used to justify cruelty." },
    ],
    timeline: [
      { label: "c. 1818", title: "Born into slavery", detail: "On a Maryland plantation; taken from his mother as an infant." },
      { label: "1826", title: "Sent to Baltimore", detail: "City life and the first, soon-forbidden, reading lessons." },
      { label: "1833", title: "Hired to Covey", detail: "A year with a professional 'slave-breaker' nearly destroys him." },
      { label: "1834", title: "The fight", detail: "He resists Covey and is never whipped again." },
      { label: "1838", title: "Escape to freedom", detail: "Reaches New York, marries, and settles in Massachusetts as an abolitionist." },
    ],
    characters: [
      { name: "Frederick Douglass", role: "Author & subject", description: "Recounts his own path from enslaved child to free abolitionist through literacy and resistance.", connections: ["Sophia Auld", "Edward Covey"] },
      { name: "Sophia Auld", role: "Enslaver's wife", description: "Begins teaching Douglass to read out of kindness, then — under her husband's influence — turns cruel.", connections: ["Frederick Douglass", "Hugh Auld"] },
      { name: "Hugh Auld", role: "Enslaver", description: "Forbids Douglass's lessons, inadvertently revealing that literacy is the road to freedom.", connections: ["Frederick Douglass", "Sophia Auld"] },
      { name: "Edward Covey", role: "The 'slave-breaker'", description: "Paid to crush enslaved people's will; Douglass's fight with him is the book's turning point.", connections: ["Frederick Douglass"] },
    ],
    mindMap: [
      { id: "root", label: "Narrative of Frederick Douglass", parent: null },
      { id: "slavery", label: "The System of Slavery", parent: "root" },
      { id: "literacy", label: "Literacy", parent: "root" },
      { id: "resistance", label: "Resistance", parent: "root" },
      { id: "freedom", label: "Freedom", parent: "root" },
      { id: "identity", label: "Erased Identity", parent: "slavery" },
      { id: "forbidden", label: "The Forbidden Book", parent: "literacy" },
      { id: "covey", label: "The Fight with Covey", parent: "resistance" },
      { id: "religion", label: "False Religion", parent: "slavery" },
    ],
    sketches: [
      { caption: "A boy sounding out letters by candlelight", emoji: "🕯️" },
      { caption: "A worn copy of 'The Columbian Orator'", emoji: "📕" },
      { caption: "Broken chains on an open road north", emoji: "⛓️" },
    ],
    qa: [
      { q: "Why did he write it?", a: "Partly to advance abolition, and partly to prove the book itself was possible — skeptics claimed no formerly enslaved person could write so well, so he named names, dates and places." },
      { q: "What's the turning point?", a: "The fight with Covey. Douglass says it was the moment slavery's hold on his mind broke, even though legal freedom was still years away." },
      { q: "Why does he hide his escape route?", a: "So that others could still use it. He criticises abolitionists who publicised escape methods and closed them off." },
    ],
  },

  {
    slug: "dracula",
    title: "Dracula",
    author: "Bram Stoker",
    year: "1897",
    category: "fiction",
    tags: ["Gothic", "Horror", "Classic"],
    cover: { emoji: "🦇" },
    tagline: "An ancient evil sails west into the modern world.",
    readingTime: "15 min read",
    rating: 4.5,
    cached: true,
    overview:
      "Told entirely through letters, diaries, telegrams and news clippings, Dracula follows a small group who discover that a Transylvanian count is a centuries-old vampire — and that he has moved to England to spread his curse. It set the template for modern vampire fiction and channels Victorian anxieties about science, sexuality, immigration and faith.",
    summary: [
      "The solicitor Jonathan Harker travels to Count Dracula's castle to finalise a property purchase and slowly realises he is a prisoner, and that his host is not human. He barely escapes.",
      "Dracula reaches England by ship and preys first on Lucy Westenra, who wastes away despite transfusions and dies — then rises as a vampire and is destroyed by her suitors and the Dutch professor Abraham Van Helsing.",
      "The count turns to Harker's wife Mina. The group pursues him with a blend of old faith (crucifixes, communion wafers, garlic) and new technology (typewriters, phonographs, train timetables, blood transfusion). They chase him back to Transylvania and kill him at his castle gate as the sun sets.",
    ],
    chapters: [
      { number: 1, title: "Harker's Journal", summary: "A young solicitor journeys to a remote castle; the locals cross themselves and give him a crucifix." },
      { number: 4, title: "The Prisoner", summary: "Harker confirms he is trapped, sees Dracula scale the wall like a lizard, and glimpses three vampire women." },
      { number: 8, title: "Lucy's Decline", summary: "In Whitby, a derelict ship runs aground; soon after, Lucy sleepwalks and weakens from two small wounds." },
      { number: 13, title: "The Bloofer Lady", summary: "The undead Lucy stalks children on Hampstead Heath; Van Helsing leads the group to release her soul." },
      { number: 21, title: "Mina's Turn", summary: "Dracula forces Mina to drink his blood, binding them — but the link also lets the hunters track him." },
      { number: 27, title: "The Pursuit", summary: "A race across Europe ends at the castle; the count is destroyed at the last moment of daylight." },
    ],
    lessons: [
      { title: "Evil adapts", detail: "Dracula thrives precisely because he studies and exploits modern systems — property law, shipping, cities." },
      { title: "Knowledge shared beats power hoarded", detail: "The hunters win by pooling their fragmentary records into one coordinated account." },
      { title: "Old and new together", detail: "Neither folk faith nor technology alone defeats the count; the story insists both are needed." },
      { title: "Fear of the outsider", detail: "The novel dramatises Victorian anxieties — the foreign aristocrat corrupting English blood from within." },
    ],
    timeline: [
      { label: "May", title: "The castle", detail: "Harker is imprisoned in Transylvania and narrowly escapes." },
      { label: "August", title: "The Demeter", detail: "A crewless ship carrying Dracula's coffins wrecks at Whitby." },
      { label: "September", title: "Lucy dies", detail: "She succumbs, rises as a vampire, and is put to rest by her suitors." },
      { label: "October", title: "Mina attacked", detail: "Dracula binds Mina; Van Helsing's circle vows to hunt him down." },
      { label: "November", title: "Transylvania", detail: "The chase ends at the castle; the count is destroyed at sunset." },
    ],
    characters: [
      { name: "Count Dracula", role: "Antagonist", description: "A centuries-old Transylvanian vampire, courtly and patient, who moves to England to feed and multiply.", connections: ["Jonathan Harker", "Mina Harker", "Abraham Van Helsing"] },
      { name: "Abraham Van Helsing", role: "Vampire hunter", description: "A Dutch professor of medicine and folklore who diagnoses the threat and leads the counter-attack.", connections: ["Lucy Westenra", "Mina Harker", "John Seward"] },
      { name: "Mina Harker", role: "Protagonist", description: "Jonathan's wife; her diligence in compiling the group's records is what makes the hunt possible.", connections: ["Jonathan Harker", "Lucy Westenra", "Abraham Van Helsing"] },
      { name: "Jonathan Harker", role: "Protagonist", description: "The solicitor whose castle ordeal opens the novel; later part of the pursuit.", connections: ["Count Dracula", "Mina Harker"] },
      { name: "Lucy Westenra", role: "First victim", description: "Mina's friend, courted by three men; her death and undeath galvanise the hunters.", connections: ["Mina Harker", "Abraham Van Helsing"] },
    ],
    mindMap: [
      { id: "root", label: "Dracula", parent: null },
      { id: "evil", label: "Ancient Evil", parent: "root" },
      { id: "modern", label: "The Modern World", parent: "root" },
      { id: "faith", label: "Faith & Folklore", parent: "root" },
      { id: "fear", label: "Victorian Fears", parent: "root" },
      { id: "count", label: "The Count's Method", parent: "evil" },
      { id: "tech", label: "Typewriters & Trains", parent: "modern" },
      { id: "cross", label: "Crucifix & Wafer", parent: "faith" },
      { id: "blood", label: "Blood & Contagion", parent: "fear" },
    ],
    sketches: [
      { caption: "A castle on a crag under a full moon", emoji: "🏰" },
      { caption: "A ship running aground in a storm", emoji: "⛴️" },
      { caption: "A crucifix laid over a coffin lid", emoji: "✝️" },
    ],
    qa: [
      { q: "Why is the novel told in documents?", a: "The 'found footage' of its day — letters and diaries make the supernatural feel documented and real, and the plot literally turns on the characters assembling those records." },
      { q: "What is Dracula really about?", a: "On the surface, a monster hunt. Underneath, Victorian anxieties: foreign invasion, disease, changing roles for women, and whether science or faith rules the modern world." },
      { q: "How do they kill him?", a: "Not with a wooden stake through the heart alone — in the book he's destroyed with a bowie knife to the throat and a blade through the heart, at sunset, at his castle gate." },
    ],
  },
];

export function getBook(slug: string): Book | undefined {
  return books.find((b) => b.slug === slug);
}

export function searchBooks(query: string): Book[] {
  const q = query.trim().toLowerCase();
  if (!q) return books;
  return books.filter((b) =>
    [b.title, b.author, ...b.tags, b.category].some((f) =>
      f.toLowerCase().includes(q)
    )
  );
}
